#!/bin/bash

# Pachno post-receive hook for git, for direct access (git and pachno on same machine)
# To use, this needs to be marked executable, and copied into your git repo,
# user@server:/path/to/repo/.git/hooks $
#   cp /pachno/modules/vcs_integration/hooks/git/pachno-post-receive post-receive
#   chmod +x ./post-receive

#>>>>> User config

# projectid comes from Project Settings -> VCS Integration
projectid=1

# this is the path to the installed pachno.
pachno_bin_path=/home/...

#<<<<< End of user config

update_pachno()
{
    oldhash=$1
    newhash=$2
    refname=$3

    # Not working? uncomment the echos and see what's not arriving properly
    #echo "Attempting to update pachno with oldhash: $oldhash newhash: $newhash refname: $refname"

    # Ignore tag pushes
    if [[ "$refname" == "refs/tags/"* ]]; then
        return
    # If no previous hash is defined then we assume this is the first commit, so process all previous commits
    elif [[ "$oldhash" == "0000000000000000000000000000000000000000" ]]; then
        commitlist=`git rev-list ${newhash}`
    else
        commitlist=`git rev-list ${oldhash}..${newhash}`
    fi

    # Loop through all commits
    echo "$commitlist" | while read -r commithash
    do
        #echo "Update pachno with commit: $commithash"

        # Retrieve commit specific information.
        parrent=`git show --no-patch --format="%P" $commithash`
        name=`git show --no-patch --format="%an <%ae>" $commithash`
        log=`git show --no-patch --format="%s %b" $commithash`
        time=`git show --no-patch --format="%ct" $commithash`
        changedfiles=`git diff-tree --name-status -r $commithash --no-commit-id`

        #echo "updating with name: $name"
        #echo "updating with log: $log"
        #echo "updating with time: $time"
        #echo "updating files: $changedfiles"

        # Report commit to Pachno
        cd $pachno_bin_path
        ./bin/pachno vcs_integration:report_commit $projectid "$name" $commithash "$log" "$changedfiles" $parrent $time $refname
        cd - > /dev/null # back to git repo folder
    done
}

if [ -n "$1" -a -n "$2" ]; then
    # we seem to be in command line mode...
    update_pachno $1 $2
else
    while read oldhash newhash refname
    do
        # we seem to be operating as a git post-receive hook
        update_pachno $oldhash $newhash $refname
    done
fi


