configure:
    route: /configure
    module: configuration
    action: index
    parameters:
      section: 0
    csrf_enabled: false

configure_authentication:
    route: /configure/authentication
    module: configuration
    action: configureAuthentication
    parameters:
      config_module: core
      section: 17
    csrf_enabled: false

configure_authentication_pt2:
    route: /configure/authentication/save
    module: configuration
    action: saveAuthentication
    parameters:
      config_module: core
      section: 17
    csrf_enabled: false

configure_projects:
    route: /configure/projects
    module: configuration
    action: configureProjects
    parameters:
      config_module: core
      section: 10
    csrf_enabled: false

configure_projects_add_project:
    route: /configure/projects/add/new
    module: configuration
    action: addProject
    parameters:
      config_module: core
      section: 10
    csrf_enabled: false

configure_project_archive:
    route: /configure/project/:project_id/archive
    module: configuration
    action: archiveProject
    parameters:
      config_module: core
      section: 10
    csrf_enabled: false

configure_project_unarchive:
    route: /configure/project/:project_id/unarchive
    module: configuration
    action: unarchiveProject
    parameters:
      config_module: core
      section: 10
    csrf_enabled: false

configure_project_delete:
    route: /configure/project/:project_id/delete
    module: configuration
    action: deleteProject
    parameters:
      config_module: core
      section: 10
    csrf_enabled: false

configure_scopes:
    route: /configure/scopes
    module: configuration
    action: configurescopes
    parameters:
      config_module: core
      section: 14
    csrf_enabled: false

configure_scope:
    route: /configure/scope/:id
    module: configuration
    action: scope
    parameters:
      config_module: core
      section: 14
    csrf_enabled: false

configure_workflow_schemes:
  route: /configure/workflowschemes
  module: configuration
  action: configureWorkflowSchemes
  parameters:
    config_module: core
    section: 1
  csrf_enabled: false

configure_workflow_delete_scheme:
  route: /configure/workflowschemes/:scheme_id/delete
  module: configuration
  action: configureWorkflowSchemeDelete
  methods:
    - POST
  parameters:
    config_module: core
    section: 1
    mode: delete_scheme
  csrf_enabled: false

configure_workflow_scheme:
  route: /configure/workflowschemes/:scheme_id
  module: configuration
  action: configureWorkflowScheme
  methods:
    - POST
  parameters:
    config_module: core
    section: 1
  csrf_enabled: false

configure_workflows:
  route: /configure/workflows
  module: configuration
  action: configureWorkflows
  parameters:
    config_module: core
    section: 1
  csrf_enabled: false

configure_workflow:
  route: /configure/workflows/:workflow_id
  module: configuration
  action: configureWorkflow
  methods:
    - GET
  parameters:
    config_module: core
    section: 1
  csrf_enabled: false

configure_workflow_post:
  route: /configure/workflows/:workflow_id
  module: configuration
  action: configureWorkflowPost
  methods:
    - POST
  parameters:
    config_module: core
    section: 1
  csrf_enabled: false

configure_workflow_delete_workflow:
  route: /configure/workflows/:workflow_id/delete
  module: configuration
  action: configureWorkflowSteps
  parameters:
    config_module: core
    section: 1
    mode: delete_workflow
  csrf_enabled: false

configure_workflow_steps:
  route: /configure/workflows/:workflow_id/steps
  module: configuration
  action: configureWorkflowSteps
  methods:
    - GET
  parameters:
    config_module: core
    section: 1
  csrf_enabled: false

configure_workflow_step:
    route: /configure/workflows/:workflow_id/steps/:step_id
    module: configuration
    action: configureWorkflowStep
    methods:
      - GET
    parameters:
      config_module: core
      section: 1
    csrf_enabled: false

configure_workflow_step_post:
  route: /configure/workflows/:workflow_id/steps/:step_id
  module: configuration
  action: configureWorkflowStepPost
  methods:
    - POST
  parameters:
    config_module: core
    section: 1
    mode: edit
  csrf_enabled: false

configure_workflow_delete_step_transitions:
    route: /configure/workflows/:workflow_id/steps/:step_id/transitions
    module: configuration
    action: configureWorkflowStep
    methods:
      - DELETE
    parameters:
      config_module: core
      section: 1
      mode: delete_outgoing_transitions
    csrf_enabled: false

configure_workflow_delete_step:
    route: /configure/workflows/:workflow_id/steps/:step_id
    module: configuration
    action: configureWorkflowStep
    methods:
      - DELETE
    parameters:
      config_module: core
      section: 1
      mode: delete
    csrf_enabled: false

configure_workflow_transition:
    route: /configure/workflows/:workflow_id/transitions/:transition_id
    module: configuration
    action: configureWorkflowTransition
    parameters:
      config_module: core
      section: 1
    csrf_enabled: false

configure_workflow_transition_post:
    route: /configure/workflows/:workflow_id/transitions/:transition_id
    module: configuration
    action: configureWorkflowTransition
    methods:
      - POST
    parameters:
      config_module: core
      section: 1
      mode: edit
    csrf_enabled: false

configure_workflow_transition_delete:
    route: /configure/workflows/:workflow_id/transitions/:transition_id
    module: configuration
    action: configureWorkflowTransition
    methods:
      - DELETE
    parameters:
      config_module: core
      section: 1
      mode: delete
    csrf_enabled: false

configure_workflow_add_transition:
    route: /configure/workflows/:workflow_id/steps/:step_id/transitions
    module: configuration
    action: configureWorkflowTransition
    methods:
      - POST
    parameters:
      config_module: core
      section: 1
    csrf_enabled: false

configure_workflow_transition_validation_rule_post:
    route: /configure/workflows/:workflow_id/transitions/:transition_id/validationrules
    module: configuration
    action: configureWorkflowTransitionPost
    methods:
      - POST
    parameters:
      config_module: core
      section: 1
      mode: new_validation_rule
    csrf_enabled: false

configure_workflow_transition_validation_rule_delete:
    route: /configure/workflows/:workflow_id/transitions/:transition_id/validationrules/:rule_id
    module: configuration
    action: configureWorkflowTransition
    methods:
      - DELETE
    parameters:
      config_module: core
      section: 1
      mode: delete_validation_rule
    csrf_enabled: false

configure_workflow_transition_action_post:
    route: /configure/workflows/:workflow_id/transitions/:transition_id/actions
    module: configuration
    action: configureWorkflowTransition
    methods:
      - POST
    parameters:
      config_module: core
      section: 1
      mode: new_action
    csrf_enabled: false

configure_workflow_transition_action_delete:
    route: /configure/workflows/:workflow_id/transitions/:transition_id/actions/:action_id
    module: configuration
    action: configureWorkflowTransition
    methods:
      - DELETE
    parameters:
      config_module: core
      section: 1
      mode: delete_action
    csrf_enabled: false

configure_files:
    route: /configure/files
    module: configuration
    action: configureUploads
    parameters:
      config_module: core
      section: 3
    csrf_enabled: false

configure_permissions:
    route: /configure/permissions
    module: configuration
    action: configurePermissions
    parameters:
      config_module: core
      section: 5
    csrf_enabled: false

configure_permissions_get_configurator:
    route: '/configure/permissions/get/configurator/*'
    module: configuration
    action: getPermissionsConfigurator
    parameters:
      config_module: core
      section: 5
    csrf_enabled: false

configure_permissions_get_permissions:
    route: '/configure/permissions/get/permissions/*'
    module: configuration
    action: getPermissionsInfo
    parameters:
      config_module: core
      section: 5
    csrf_enabled: false

permissions_set_denied:
    route: /configure/permissions/set/permission/denied/for/:target_module/:key/:target_id/:target_type/:item_id/:template_mode
    module: configuration
    action: setPermission
    parameters:
      config_module: core
      section: 5
      mode: denied
    csrf_enabled: false

permissions_set_allowed:
    route: /configure/permissions/set/permission/allowed/for/:target_module/:key/:target_id/:target_type/:item_id/:template_mode
    module: configuration
    action: setPermission
    parameters:
      config_module: core
      section: 5
      mode: allowed
    csrf_enabled: false

permissions_set_unset:
    route: /configure/permissions/unset/permission/for/:target_module/:key/:target_id/:target_type/:item_id/:template_mode
    module: configuration
    action: setPermission
    parameters:
      config_module: core
      section: 5
      mode: unset
    csrf_enabled: false

configure_issuetypes:
    route: /configure/issuetypes
    module: configuration
    action: configureIssuetypes
    methods:
      - GET
    parameters:
      config_module: core
      section: 6
    csrf_enabled: false

configure_issuetypes_add:
    route: /configure/issuefields/add/issuetype
    module: configuration
    action: configureIssuetypesAction
    parameters:
      config_module: core
      section: 6
      mode: add
    csrf_enabled: false

configure_issuetypes_delete:
    route: /configure/issuefields/delete/issuetype/:id
    module: configuration
    action: configureIssuetypesAction
    parameters:
      config_module: core
      section: 6
      mode: delete
    csrf_enabled: false

configure_issuetypes_update_issuetype:
    route: /configure/issuefields/:id
    module: configuration
    action: configureIssuetypesAction
    methods: 'POST'
    parameters:
      config_module: core
      section: 6
      mode: update
    csrf_enabled: false

configure_issuetypes_update_issuetype_for_scheme:
    route: /configure/issuefields/update/issuetype/:id/for/scheme/:scheme_id
    module: configuration
    action: configureIssuetypesAction
    parameters:
      config_module: core
      section: 6
      mode: update
    csrf_enabled: false

configure_issuetypes_schemes:
    route: /configure/issuetypeschemes
    module: configuration
    action: configureIssuetypeSchemes
    parameters:
      config_module: core
      section: 9
    csrf_enabled: false

configure_issuetypes_scheme:
    route: /configure/issuetypeschemes/:scheme_id
    module: configuration
    action: configureIssuetypeScheme
    methods:
      - GET
    parameters:
      config_module: core
      section: 9
      mode: scheme
    csrf_enabled: false

configure_issuetypes_scheme_post:
    route: /configure/issuetypeschemes/:scheme_id
    module: configuration
    action: configureIssuetypeSchemePost
    methods:
      - POST
    parameters:
      config_module: core
      section: 9
      mode: scheme
    csrf_enabled: false

configure_issuetypes_scheme_options:
  route: /configure/issuetypeschemes/:scheme_id/options/:issue_type_id
  module: configuration
  action: configureIssuetypesGetOptionsForScheme
  methods:
    - GET
  parameters:
    config_module: core
    section: 6
  csrf_enabled: false

configure_issuetypes_scheme_options_post:
  route: /configure/issuetypeschemes/:scheme_id/options/:issue_type_id
  module: configuration
  action: configureIssuetypesSaveOptionsForScheme
  methods:
    - POST
  parameters:
    config_module: core
    section: 6
    mode: updatechoices
  csrf_enabled: false

configure_issuetypes_scheme_field:
  route: /configure/issuetypeschemes/:scheme_id/options/:issue_type_id/fields/:key
  module: configuration
  action: configureIssuetypesGetFieldForScheme
  methods:
    - GET
  parameters:
    config_module: core
    section: 6
  csrf_enabled: false

configure_issuetypes_disable_issuetype_for_scheme:
  route: /configure/issuetypes/disable/:id/for/scheme/:scheme_id
  module: configuration
  action: configureIssuetypesAction
  parameters:
    config_module: core
    section: 6
    mode: toggletype
    state: disable
  csrf_enabled: false

configure_issuetypes_enable_issuetype_for_scheme:
  route: /configure/issuetypes/enable/:id/for/scheme/:scheme_id
  module: configuration
  action: configureIssuetype
  parameters:
    config_module: core
    section: 6
    mode: toggletype
    state: enable
  csrf_enabled: false

configure_issuetypes_delete_scheme:
    route: /configure/issuetypes/delete/scheme/:scheme_id
    module: configuration
    action: configureIssuetypeScheme
    parameters:
      config_module: core
      section: 6
      mode: delete_scheme
    csrf_enabled: false

configure_issuefields:
    route: /configure/issuefields
    module: configuration
    action: configureIssuefields
    parameters:
      config_module: core
      section: 4
    csrf_enabled: false

configure_issuefields_getoptions:
    route: /configure/issuefields/get/options/for/:type
    module: configuration
    action: configureIssuefieldsGetOptions
    parameters:
      config_module: core
      section: 4
    csrf_enabled: false

configure_issuefields_saveorder:
    route: /configure/issuefields/save/options/order/for/:type
    module: configuration
    action: configureIssuefieldsAction
    parameters:
      config_module: core
      section: 4
      mode: saveorder
    csrf_enabled: false

configure_issuefields_edit:
    route: /configure/issuefields/edit/:type/:id
    module: configuration
    action: configureIssuefieldsAction
    parameters:
      config_module: core
      section: 4
      mode: edit
    csrf_enabled: false

configure_issuefields_add:
    route: /configure/issuefields/add/:type
    module: configuration
    action: configureIssuefieldsAction
    parameters:
      config_module: core
      section: 4
      mode: add
    csrf_enabled: false

configure_issuefields_delete:
    route: /configure/issuefields/delete/:type/:id
    module: configuration
    action: configureIssuefieldsAction
    parameters:
      config_module: core
      section: 4
      mode: delete
    csrf_enabled: false

configure_issuefields_getpermissions:
    route: /configure/issuefields/get/permissions/for/:type/:id
    module: configuration
    action: configureIssuefieldsGetPermissions
    parameters:
      config_module: core
      section: 4
    csrf_enabled: false

configure_issuefields_add_customtype:
    route: /configure/issuefields/add/custom/type
    module: configuration
    action: configureIssuefieldsCustomTypeAction
    parameters:
      config_module: core
      section: 4
      mode: add
    csrf_enabled: false

configure_issuefields_update_customtype:
    route: /configure/issuefields/update/custom/type/:type
    module: configuration
    action: configureIssuefieldsCustomTypeAction
    parameters:
      config_module: core
      section: 4
      mode: update
    csrf_enabled: false

configure_issuefields_delete_customtype:
    route: /configure/issuefields/delete/custom/type/:type
    module: configuration
    action: configureIssuefieldsCustomTypeAction
    parameters:
      config_module: core
      section: 4
      mode: delete
    csrf_enabled: false

configure_users_clone_group:
    route: /configure/groups/:group_id/clone
    module: configuration
    action: addGroup
    methods:
      - POST
    parameters:
      config_module: core
      section: 2
      mode: clone
    csrf_enabled: false

configure_users_delete_group:
    route: /configure/groups/:group_id
    module: configuration
    action: deleteGroup
    methods:
      - DELETE
    parameters:
      config_module: core
      section: 2
    csrf_enabled: false

configure_users_update_user_scopes:
    route: /configure/users/update/userscopes/:user_id
    module: configuration
    action: updateUserScopes
    parameters:
      config_module: core
      section: 2
    csrf_enabled: false

configure_users_delete_user:
    route: /configure/users/delete/user/:user_id
    module: configuration
    action: deleteUser
    parameters:
      config_module: core
      section: 2
    csrf_enabled: false

configure_modules:
    route: /configure/modules
    module: configuration
    action: configureModules
    parameters:
      config_module: core
      section: 15
    csrf_enabled: false

configure_module:
    route: /configure/module/:config_module
    module: configuration
    action: configureModule
    parameters:
      config_module: core
      section: 15
    csrf_enabled: false

configure_users_import_user:
    route: /configure/users/import/user
    module: configuration
    action: addUser
    parameters:
      config_module: core
      mode: import
      section: 2
    csrf_enabled: false

configure_site_icons:
    route: /configure/settings/icons
    module: configuration
    action: siteIcons
    parameters: [ ]
    csrf_enabled: false
